In [344]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [402]:
car=pd.read_csv('C:/Users/Arjun/Downloads/cardataset.csv')
life=pd.read_csv('C:/Users/Arjun/Downloads/lifeexpectancy.csv')

In [403]:

def predict_train():
    global X_train,y_train,m,b
    cal=np.array(X_train)@m.T+b
    return cal
def predict(X_any):
    cal=cal=np.array(X_any)@m.T+b
    return cal

In [404]:
def diff_cost(y_pred,y,i):
    global X_train
    d_c=((X_train[:,i ].reshape((-1,1))).T@(y_pred-y))/len(y)
    return d_c
def cost(y_pred,y):
    c=np.sum((y-y_pred)**2)/len(y)
    return c

In [405]:
def grad_desc():
    global X_train,y_train,m,c1,b,flag
    for i in range(m.shape[1]):
        while(1):
            m[0,i]=m[0,i]-0.5*diff_cost(predict_train(),y_train,i)
            error=cost(predict_train(),y_train)
            if(error>=c1):
                c1=error    
            else:
                break
    while(1):
        b=b-0.7*((np.sum(predict_train()-y_train))/len(y_train))
        error=cost(predict_train(),y_train)
        if(error>=c1):
                c1=error
        else:
                break

In [406]:
def linear_regression():
    global X_train,y_train,m,b,c1,flag
    b=0
    n=X_train.shape[1]
    m=np.zeros((1,n))
    y_f=predict_train()
    c1=cost(y_f,y_train)
    flag=c1
    grad_desc()

In [407]:
life.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
Country                           2938 non-null object
Year                              2938 non-null int64
Status                            2938 non-null object
Life_expectancy                   2928 non-null float64
Adult_Mortality                   2928 non-null float64
infant_deaths                     2938 non-null int64
Alcohol                           2744 non-null float64
percentage_expenditure            2938 non-null float64
Hepatitis_B                       2385 non-null float64
Measles                           2938 non-null int64
BMI                               2904 non-null float64
under-five_deaths                 2938 non-null int64
Polio                             2919 non-null float64
Total_expenditure                 2712 non-null float64
Diphtheria                        2919 non-null float64
HIV/AIDS                          2938 non-null float64
GDP                               2490 non-null float64
Population                        2286 non-null float64
thinness_1-19_years               2904 non-null float64
thinness_5-9_years                2904 non-null float64
Income_compositio_of_resources    2771 non-null float64
Schooling                         2775 non-null float64
dtypes: float64(16), int64(4), object(2)
memory usage: 505.0+ KB

In [408]:
for i in life.drop(['Country','Status'],axis=1).columns:
    life[i].fillna(np.mean(life[i]),inplace=True)

In [409]:
life.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
Country                           2938 non-null object
Year                              2938 non-null int64
Status                            2938 non-null object
Life_expectancy                   2938 non-null float64
Adult_Mortality                   2938 non-null float64
infant_deaths                     2938 non-null int64
Alcohol                           2938 non-null float64
percentage_expenditure            2938 non-null float64
Hepatitis_B                       2938 non-null float64
Measles                           2938 non-null int64
BMI                               2938 non-null float64
under-five_deaths                 2938 non-null int64
Polio                             2938 non-null float64
Total_expenditure                 2938 non-null float64
Diphtheria                        2938 non-null float64
HIV/AIDS                          2938 non-null float64
GDP                               2938 non-null float64
Population                        2938 non-null float64
thinness_1-19_years               2938 non-null float64
thinness_5-9_years                2938 non-null float64
Income_compositio_of_resources    2938 non-null float64
Schooling                         2938 non-null float64
dtypes: float64(16), int64(4), object(2)
memory usage: 505.0+ KB

In [410]:
lifeimp=life.drop(['Adult_Mortality','infant_deaths','Measles','under-five_deaths','HIV/AIDS','Population','thinness_1-19_years','thinness_5-9_years'],axis=1)

In [411]:
lifeimp.corr()
y=life['Life_expectancy']
life.drop('Life_expectancy',inplace=True,axis=1)

In [412]:
df=lifeimp[['Country','Status']]
lifeimp.drop(['Country','Status'],axis=1,inplace=True)

In [413]:
for i in lifeimp.columns:
    lifeimp[i]=(lifeimp[i]-min(lifeimp[i]))/(min(lifeimp[i])-max(lifeimp[i]))
lifeimp.head()

,Year,Life_expectancy,Alcohol,percentage_expenditure,Hepatitis_B,BMI,Polio,Total_expenditure,Diphtheria,GDP,Income_compositio_of_resources,Schooling
0,-1.000000,-0.544592,-0.0,-0.003659,-0.653061,-0.209733,-0.031250,-0.452118,-0.649485,-0.004889,-0.505274,-0.487923
1,-0.933333,-0.447818,-0.0,-0.003774,-0.622449,-0.203940,-0.572917,-0.453279,-0.618557,-0.005127,-0.502110,-0.483092
2,-0.866667,-0.447818,-0.0,-0.003759,-0.642857,-0.198146,-0.614583,-0.450377,-0.639175,-0.005287,-0.495781,-0.478261
3,-0.800000,-0.440228,-0.0,-0.004014,-0.673469,-0.192352,-0.666667,-0.473012,-0.670103,-0.005608,-0.488397,-0.473430
4,-0.733333,-0.434535,-0.0,-0.000364,-0.683673,-0.187717,-0.677083,-0.435287,-0.680412,-0.000519,-0.478903,-0.458937

In [414]:
t=pd.get_dummies(df.Country)
t

,Afghanistan,Albania,Algeria,Angola,Antigua and Barbuda,Argentina,Armenia,Australia,Austria,Azerbaijan,...,United Republic of Tanzania,United States of America,Uruguay,Uzbekistan,Vanuatu,Venezuela (Bolivarian Republic of),Viet Nam,Yemen,Zambia,Zimbabwe
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2908,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2909,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2910,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2911,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2912,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2913,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2914,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2915,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2916,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2917,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2918,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2919,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2920,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2921,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2922,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2923,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2924,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2925,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2926,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2927,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2928,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2929,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2930,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2931,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2932,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2933,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2934,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2935,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2936,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2937,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [415]:
lifeimp=pd.concat([lifeimp,t],axis=1)

In [416]:
lifeimp.columns

Index(['Year', 'Life_expectancy', 'Alcohol', 'percentage_expenditure',
       'Hepatitis_B', 'BMI', 'Polio', 'Total_expenditure', 'Diphtheria', 'GDP',
       ...
       'United Republic of Tanzania', 'United States of America', 'Uruguay',
       'Uzbekistan', 'Vanuatu', 'Venezuela (Bolivarian Republic of)',
       'Viet Nam', 'Yemen', 'Zambia', 'Zimbabwe'],
      dtype='object', length=205)

In [417]:
countries=[]
for i in t.columns:
    if np.corrcoef(y,lifeimp[i])[0,1]>0.06:
        print(i,np.corrcoef(y,lifeimp[i])[0,1])
    else:
        countries.append(i)

Australia 0.09798574887618974
Austria 0.09540719052987762
Belgium 0.08917972886331275
Canada 0.09701270799078898
Chile 0.07959527614211481
Costa Rica 0.07292994607711963
Cuba 0.06811339369438567
Cyprus 0.08134674973583626
Denmark 0.07808706276974353
Finland 0.08942298908466259
France 0.10114813175374204
Germany 0.0930232403606458
Greece 0.09336380467053607
Iceland 0.1028996053474637
Ireland 0.08504430510035929
Israel 0.09399628124604646
Italy 0.10090487153239201
Japan 0.10362938601151415
Luxembourg 0.0899581615716334
Malta 0.08669847460554053
Netherlands 0.09268267605075549
New Zealand 0.09428819351166674
Norway 0.09783979274337919
Portugal 0.08382800399360822
Qatar 0.06076693500960967
Republic of Korea 0.08767151549094122
Singapore 0.09535853848560778
Slovenia 0.08178461813426673
Spain 0.09998048269126125
Sweden 0.10348342987870451
Switzerland 0.10202386855060336
United Kingdom of Great Britain and Northern Ireland 0.09005546566017349
United States of America 0.06879452231416631

In [418]:
lifeimp.drop(countries,axis=1,inplace=True)
lifeimp.drop('Life_expectancy',inplace=True,axis=1)
len(lifeimp.columns)

44

In [419]:
status=pd.get_dummies(df.Status)

In [420]:
lifeimp=pd.concat([lifeimp,status],axis=1)

In [421]:
lifeimp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 46 columns):
Year                                                    2938 non-null float64
Alcohol                                                 2938 non-null float64
percentage_expenditure                                  2938 non-null float64
Hepatitis_B                                             2938 non-null float64
BMI                                                     2938 non-null float64
Polio                                                   2938 non-null float64
Total_expenditure                                       2938 non-null float64
Diphtheria                                              2938 non-null float64
GDP                                                     2938 non-null float64
Income_compositio_of_resources                          2938 non-null float64
Schooling                                               2938 non-null float64
Australia                                               2938 non-null uint8
Austria                                                 2938 non-null uint8
Belgium                                                 2938 non-null uint8
Canada                                                  2938 non-null uint8
Chile                                                   2938 non-null uint8
Costa Rica                                              2938 non-null uint8
Cuba                                                    2938 non-null uint8
Cyprus                                                  2938 non-null uint8
Denmark                                                 2938 non-null uint8
Finland                                                 2938 non-null uint8
France                                                  2938 non-null uint8
Germany                                                 2938 non-null uint8
Greece                                                  2938 non-null uint8
Iceland                                                 2938 non-null uint8
Ireland                                                 2938 non-null uint8
Israel                                                  2938 non-null uint8
Italy                                                   2938 non-null uint8
Japan                                                   2938 non-null uint8
Luxembourg                                              2938 non-null uint8
Malta                                                   2938 non-null uint8
Netherlands                                             2938 non-null uint8
New Zealand                                             2938 non-null uint8
Norway                                                  2938 non-null uint8
Portugal                                                2938 non-null uint8
Qatar                                                   2938 non-null uint8
Republic of Korea                                       2938 non-null uint8
Singapore                                               2938 non-null uint8
Slovenia                                                2938 non-null uint8
Spain                                                   2938 non-null uint8
Sweden                                                  2938 non-null uint8
Switzerland                                             2938 non-null uint8
United Kingdom of Great Britain and Northern Ireland    2938 non-null uint8
United States of America                                2938 non-null uint8
Developed                                               2938 non-null uint8
Developing                                              2938 non-null uint8
dtypes: float64(11), uint8(35)
memory usage: 353.0 KB

In [422]:
from sklearn.model_selection import train_test_split

In [423]:
X_train,X_test,y_train,y_test=train_test_split(np.array(lifeimp),y,train_size=0.7)

C:\Users\Arjun\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)

In [424]:
X_train=np.array(X_train)
X_test=np.array(X_test)
y_test=np.array(y_test).reshape(-1,1)
y_train=np.array(y_train).reshape(-1,1)
print(X_test.shape)
print(X_train.shape)
print(y_test.shape)

(882, 46)
(2056, 46)
(882, 1)

In [425]:
linear_regression()

In [426]:
y_pred=predict_train()

In [445]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import classification_report

In [444]:
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred_inst=lr.predict(X_test)
print(r2_score(y_pred_1,y_test))

0.26304211014425305

In [429]:
y_pred_1=predict_test(X_test)
y_pred_1.shape

(882, 1)

In [430]:
cost(y_pred_1,y_test)

124.54639961388246

In [431]:
cost(y_pred_inst,y_test)

27.28959823515109

In [432]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
Car_Name         301 non-null object
Year             301 non-null int64
Selling_Price    301 non-null float64
Present_Price    301 non-null float64
Kms_Driven       301 non-null int64
Fuel_Type        301 non-null object
Seller_Type      301 non-null object
Transmission     301 non-null object
Owner            301 non-null int64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.2+ KB

In [433]:
car.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [443]:
(car['Car_Name'].value_counts()>4).count()

98